Update jtos

diff --git a/jtos b/jtos
--- a/jtos
+++ b/jtos
@@ -90,12 +90,9 @@ install_path=$(pwd)
 [ ! -d /usr/share/backgrounds ] && sudo mkdir -p /usr/share/backgrounds
 
 clear
-while true; do
-    read -p "Do you want to install Xmonad? [Y/n] " yn
-    case $yn in
-        [Yy]* ) 
+read -p "Do you want to install Xmonad... (y/n)? "
+if [ "$REPLY" = "y" ]; then
 	sudo pacman -Sy xmonad xmonad-contrib xmobar
-        sleep 5
         [ ! -d ~/.config/xmobar ] && mkdir -p ~/.config/xmobar
         [ ! -d ~/.config/xmonad ] && mkdir -p ~/.config/xmonad
         mv $install_path/xmobarrc ~/.config/xmobar/
@@ -109,13 +106,10 @@ while true; do
 		xmonad --recompile
 	}
 
-	xmonad_recompile || echo "Recompiling Xmonad failed!"
-	;;
-        [Nn]* ) break;;
-        "" ) sudo reboot;;
-        * ) echo "Please answer yes or no.";;
-    esac
-done
+	xmonad_recompile || echo "Recompiling Xmonad failed!"	
+else
+	cancel
+fi
 
 clear
 while true; do
